trigger:
- main
- feature

pool: Soonal_pool


stages:

- stage: terraforminstall
  displayName: Install Terraform
  jobs:
  - job: install
    displayName: Install Terraform
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'


- stage: Scanning_stage
  displayName: Terraform Security Scan
  dependsOn: terraforminstall
  jobs:
  - job: Tfsec
    displayName: Run tfsec Scan
    steps:
    - script: |
        tfsec .
      displayName: tfsec Security Scan


- stage: TerraformInit
  displayName: Terraform Init and Plan
  dependsOn: Scanning_stage

  jobs:
  - job: TerraformInit
    displayName: Terraform Init
    steps:

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'environment/dev'
        backendServiceArm: 'new_connection'
        backendAzureRmResourceGroupName: 'rgs'
        backendAzureRmStorageAccountName: 'ranjeetstg'
        backendAzureRmContainerName: 'Containers'
        backendAzureRmKey: 'dev12.state'


    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'environment/dev'
        environmentServiceNameAzureRM: 'new_connection'