trigger:
- main

pool: Soonal_pool


stages:
  - stage: terraform_install
    jobs: 
     - job: 
       steps: 
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

  - stage: terraform_init
    jobs: 
     - job: 
       steps: 
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           displayName: init
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/envoronmrnt/dev'
           backendServiceArm: 'new_connection'
           backendAzureRmResourceGroupName: 'rgs'
           backendAzureRmStorageAccountName: 'ranjeetstgs123'
           backendAzureRmContainerName: 'rcontainer'
           backendAzureRmKey: 'rs.tfstate'

      
       