trigger: 
- main
- feature/*

pool: soonal_pool

stages:
- stage: Install
  jobs:
    - job: InstallTerraform
      displayName: yaha pe terraform install hoga
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'



- stage: init
  jobs: 
   - job: Terraforminit
     displayName: yaha pe terrafom init chalega
     steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
         backendServiceArm: 'new_connection'
         backendAzureRmStorageAccountName: 'ranjeetstgs123'
         backendAzureRmContainerName: 'rcontainer'
         backendAzureRmKey: 'rs.tfstate'
- stage: Validate
  jobs:
  - job: ValidateTerraform
    displayName: yaha pe validate command chalega 
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'

- stage: plan
  jobs: 
  - job: terraformplan
    displayName: yaha terraformplan chalega

    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        backendServiceArm: 'new_connection'
        backendAzureRmStorageAccountName: 'ranjeetstgs123'
        backendAzureRmContainerName: 'rcontainer'
        backendAzureRmKey: 'rs.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'new_connection'